routes/web.php
<?php

use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\Auth\SocialLoginController;
use App\Http\Controllers\ScheduleController;
use App\Http\Controllers\SendMailController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\TemplateController;
use App\Http\Middleware\AuthLogin;
use App\Http\Middleware\IfAlreadyLogin;
use App\Models\Template;
use Carbon\Carbon;
use Cron\CronExpression;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
Route::get('/', static function () {
    return redirect()->route('auth.login');
});

Route::group(['prefix' => 'auth', 'as' => 'auth.', 'middleware' => [IfAlreadyLogin::class]], static function() {

    Route::get('/login', [AuthController::class, 'login'])->name('login');
    Route::post('/login', [AuthController::class, 'processLogin'])->name('process_login');
    Route::get('/forgot_password', [AuthController::class, 'forgotPassword'])->name('forgot_password');
    Route::post('/reset_password', [AuthController::class, 'processResetPassword'])->name('reset_password');
    Route::post('/verify_reset_password', [AuthController::class, 'verifyResetPassword'])->name('verify_reset_password');
    Route::post('/update_password', [AuthController::class, 'updatePassword'])->name('update_password');
    Route::get('/register', [AuthController::class, 'register'])->name('register');
    Route::post('/register', [AuthController::class, 'processRegister'])->name('process_register');
    Route::post('/verify_register', [AuthController::class, 'verifyRegister'])->name('verify_register');
    Route::post('/verify_new_location', [AuthController::class, 'verifyNewLocation'])->name('verify_new_location');
    Route::get('/{social}/redirect', [SocialLoginController::class, 'redirect'])->name('redirect');
    Route::get('/{social}/callback', [SocialLoginController::class, 'callback'])->name('callback');
});
Route::get('/logout', [AuthController::class, 'logout'])->name('auth.logout');

Route::group(['middleware' => [AuthLogin::class]], static function () {
    Route::group(['prefix' => 'template', 'as' => 'template.'], static function () {
        Route::get('/', [TemplateController::class, 'index'])->name('index');
        Route::get('/create', [TemplateController::class, 'create'])->name('create');
        Route::post('/create', [TemplateController::class, 'store'])->name('store');
        Route::get('/edit/{template}', [TemplateController::class, 'edit'])->name('edit');
        Route::put('/update/{template}', [TemplateController::class, 'update'])->name('update');
        Route::delete('/{template}', [TemplateController::class, 'destroy'])->name('destroy');
    });
    Route::group(['prefix' => 'schedule', 'as' => 'schedule.'], static function () {
        Route::put('/toggle_active/{template}', [ScheduleController::class, 'toggleActive'])->name('toggle_active');
    });
    Route::group(['prefix' => 'setting', 'as' => 'setting.'], static function () {
        Route::put('/update', [SettingController::class, 'update'])->name('update');
    });

});


Route::get('/test', function () {
    $cron = new CronExpression('0 */1 * * *');
    $next_queue_time = $cron->getNextRunDate()->format('Y-m-d H:i:s');
    $next_queue = Carbon::make($next_queue_time)->toDateTimeString();
    dd($next_queue);
})->name('test');

resources/views/app-theme/header.blade.php
<div class="top-bar">

    <nav aria-label="breadcrumb" class="-intro-x mr-auto hidden sm:flex">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route($route)}}">{{$menu}}</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{$breadcrumb}}</li>
        </ol>
    </nav>


    <div class="intro-x relative mr-3 sm:mr-6">
        <div class="search hidden sm:block">
            <input type="text" class="search__input form-control border-transparent" placeholder="Không tìm kiếm được đâu...">
            <i data-lucide="search" class="search__icon dark:text-slate-500"></i>
        </div>
        <a class="notification sm:hidden" href="">
            <i data-lucide="search" class="notification__icon dark:text-slate-500"></i>
        </a>
    </div>


    <div class="intro-x dropdown mr-auto sm:mr-6">
    </div>


    <div class="intro-x relative mr-3 sm:mr-6">
        <div class="form-check form-switch">
            <input @if(isDarkMode()) checked @endif id="toggle-theme" class="form-check-input" type="checkbox">
            <label class="form-check-label" for="checkbox-switch-7">Chế độ tối</label>
        </div>
    </div>


    <div class="intro-x dropdown w-8 h-8">
        <div class="dropdown-toggle w-8 h-8 rounded-full overflow-hidden shadow-lg image-fit zoom-in" role="button" aria-expanded="false" data-tw-toggle="dropdown">
            <img alt="MaoLeng - EmailDaily" src="{{authed()->avatar}}">
        </div>
        <div class="dropdown-menu w-56">
            <ul class="dropdown-content bg-primary text-white">
                <li class="p-2">
                    <div class="font-medium">{{authed()->name}}</div>
                </li>
                <li>
                    <hr class="dropdown-divider border-white/[0.08]">
                </li>
                <li>
                    <a href="" class="dropdown-item hover:bg-white/5">
                        <i data-lucide="user" class="w-4 h-4 mr-2"></i> Trang cá nhân
                    </a>
                </li>
{{--                <li>--}}
{{--                    <a href="" class="dropdown-item hover:bg-white/5">--}}
{{--                        <i data-lucide="edit" class="w-4 h-4 mr-2"></i> Add Account--}}
{{--                    </a>--}}
{{--                </li>--}}
{{--                <li>--}}
{{--                    <a href="" class="dropdown-item hover:bg-white/5">--}}
{{--                        <i data-lucide="lock" class="w-4 h-4 mr-2"></i> Reset Password--}}
{{--                    </a>--}}
{{--                </li>--}}
{{--                <li>--}}
{{--                    <a href="" class="dropdown-item hover:bg-white/5">--}}
{{--                        <i data-lucide="help-circle" class="w-4 h-4 mr-2"></i> Help--}}
{{--                    </a>--}}
{{--                </li>--}}
                <li>
                    <hr class="dropdown-divider border-white/[0.08]">
                </li>
                <li>
                    <a href="{{route('auth.logout')}}" class="dropdown-item hover:bg-white/5">
                        <i data-lucide="toggle-right" class="w-4 h-4 mr-2"></i> Đăng xuất
                    </a>
                </li>
            </ul>
        </div>
    </div>

</div>

resources/views/app-theme/master.blade.php
<!DOCTYPE html>
<html lang="en" class="@if(isDarkMode()) dark @else light @endif theme">
    @include('app-theme.page')

    <body class="py-5">
        @include('app-theme.sidebar-mb')
        <div class="flex mt-[4.7rem] md:mt-0">
            @include('app-theme.sidebar-pc')
            <div class="content">
                @include('app-theme.header')
                <div class="intro-y flex items-center mt-8">
                    <h2 class="text-lg font-medium mr-auto">@yield('title')</h2>
                </div>
                <div class="grid grid-cols-12 gap-6 mt-5">
                    @yield('content')
                </div>
            </div>
        </div>

    <script src="{{asset('app/js/app.js')}}"></script>
    <script src="{{asset('app/js/jquery-3.6.0.js')}}"></script>
    <script>
        let theme =
        $("#toggle-theme").click(function () {
            let theme = $("#toggle-theme").is(':checked') ? 'dark' : 'light'
            $.ajax({
                type:'PUT',
                url:'{{route('setting.update')}}',
                data: {
                    _token: "{{csrf_token()}}",
                    user_id: "{{authed()->id}}",
                    key: 'theme',
                    value: theme,
                },
                success:function(data) {
                    window.location.reload()
                }
            });
        })
    </script>
    @yield('script')
    </body>
</html>

resources/views/app-theme/page.blade.php
<head>
    <meta charset="utf-8">
    <link href="" rel="shortcut icon">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Email Daily</title>
    <link rel="stylesheet" href="{{asset('app/css/app.css')}}" />
</head>

resources/views/app-theme/sidebar-mb.blade.php
<div class="mobile-menu md:hidden">
    <div class="mobile-menu-bar">
        <a href="{{route('template.index')}}" class="flex mr-auto">
            <img alt="Mao Leng" class="w-6" src="{{asset('app/images/logo.png')}}" style="width:40px">
        </a>
        <a href="javascript:;" class="mobile-menu-toggler">
            <i data-lucide="bar-chart-2" class="w-8 h-8 text-white transform -rotate-90"></i>
        </a>
    </div>
    <div class="scrollable">
        <a href="{{route('template.index')}}" class="mobile-menu-toggler">
            <i data-lucide="x-circle" class="w-8 h-8 text-white transform -rotate-90"></i>
        </a>
        <ul class="scrollable__content py-2">
            <li>
                <a href="javascript:;" class="menu menu--active">
                    <div class="menu__icon">
                        <i data-lucide="home"></i>
                    </div>
                    <div class="menu__title">
                        Mẫu tin nhắn
                    </div>
                </a>
            </li>



        </ul>
    </div>
</div>

resources/views/app-theme/sidebar-pc.blade.php
<nav class="side-nav">
    <a href="{{route('template.index')}}" class="intro-x flex items-center pl-5 pt-4">
        <img alt="Mao Leng" class="w-6" src="{{asset('app/images/logo.png')}}" style="width:40px">
        <span class="hidden xl:block text-white text-lg ml-3">
            MaoLeng
        </span>
    </a>
    <div class="side-nav__devider my-6"></div>
    <ul>
        <li>
            <a href="{{route('template.index')}}" class="side-menu side-menu--active">
                <div class="side-menu__icon">
                    <i data-lucide="home"></i>
                </div>
                <div class="side-menu__title">
                    Mẫu tin nhắn
                </div>
            </a>
        </li>



    </ul>
</nav>