routes/web.php
<?php

use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\Auth\SocialLoginController;
use App\Http\Controllers\ScheduleController;
use App\Http\Controllers\SendMailController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\TemplateController;
use App\Http\Middleware\AuthLogin;
use App\Http\Middleware\IfAlreadyLogin;
use App\Models\Template;
use Carbon\Carbon;
use Cron\CronExpression;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
Route::get('/', static function () {
    return redirect()->route('auth.login');
});

Route::group(['prefix' => 'auth', 'as' => 'auth.', 'middleware' => [IfAlreadyLogin::class]], static function() {

    Route::get('/login', [AuthController::class, 'login'])->name('login');
    Route::post('/login', [AuthController::class, 'processLogin'])->name('process_login');
    Route::get('/forgot_password', [AuthController::class, 'forgotPassword'])->name('forgot_password');
    Route::post('/reset_password', [AuthController::class, 'processResetPassword'])->name('reset_password');
    Route::post('/verify_reset_password', [AuthController::class, 'verifyResetPassword'])->name('verify_reset_password');
    Route::post('/update_password', [AuthController::class, 'updatePassword'])->name('update_password');
    Route::get('/register', [AuthController::class, 'register'])->name('register');
    Route::post('/register', [AuthController::class, 'processRegister'])->name('process_register');
    Route::post('/verify_register', [AuthController::class, 'verifyRegister'])->name('verify_register');
    Route::post('/verify_new_location', [AuthController::class, 'verifyNewLocation'])->name('verify_new_location');
    Route::get('/{social}/redirect', [SocialLoginController::class, 'redirect'])->name('redirect');
    Route::get('/{social}/callback', [SocialLoginController::class, 'callback'])->name('callback');
});
Route::get('/logout', [AuthController::class, 'logout'])->name('auth.logout');

Route::group(['middleware' => [AuthLogin::class]], static function () {
    Route::group(['prefix' => 'template', 'as' => 'template.'], static function () {
        Route::get('/', [TemplateController::class, 'index'])->name('index');
        Route::get('/create', [TemplateController::class, 'create'])->name('create');
        Route::post('/create', [TemplateController::class, 'store'])->name('store');
        Route::get('/edit/{template}', [TemplateController::class, 'edit'])->name('edit');
        Route::put('/update/{template}', [TemplateController::class, 'update'])->name('update');
        Route::delete('/{template}', [TemplateController::class, 'destroy'])->name('destroy');
    });
    Route::group(['prefix' => 'schedule', 'as' => 'schedule.'], static function () {
        Route::put('/toggle_active/{template}', [ScheduleController::class, 'toggleActive'])->name('toggle_active');
    });
    Route::group(['prefix' => 'setting', 'as' => 'setting.'], static function () {
        Route::put('/update', [SettingController::class, 'update'])->name('update');
    });

});


Route::get('/test', function () {
    $cron = new CronExpression('0 */1 * * *');
    $next_queue_time = $cron->getNextRunDate()->format('Y-m-d H:i:s');
    $next_queue = Carbon::make($next_queue_time)->toDateTimeString();
    dd($next_queue);
})->name('test');

app/Models/Template.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;

class Template extends Base
{
    use HasFactory;

    public const BANNER = 'https://i.pinimg.com/564x/13/b2/c5/13b2c5d0b06b2ee135ce911dbe37144e.jpg';

    protected $fillable = [
        'title', 'content', 'sender', 'banner', 'active', 'user_id'
    ];

    protected $casts = [
        'active' => 'boolean',
    ];

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }

    public function schedule(): HasOne
    {
        return $this->hasOne(Schedule::class, 'template_id', 'id');
    }

    public function images(): HasMany
    {
        return $this->hasMany(Image::class, 'template_id', 'id');
    }

    public function getId2Attribute(): string
    {
        return substr($this->id, 0, 5);
    }

}

resources/views/app/template/create.blade.php
@extends('app-theme.master')

@section('title')
    Thêm mẫu tin nhắn
@endsection

@section('content')
    <form action="{{route('template.create')}}" id="form" method="post" class="intro-y col-span-12 lg:col-span-6">
        <div class="intro-y col-span-12 lg:col-span-6">
            @csrf
            <div class="intro-y box p-5">
                <h2 class="font-medium text-base mr-auto">Nội dung mẫu tin nhắn</h2>
                <br>
                <div>
                    <label for="crud-form-1" class="form-label">Tiêu đề</label>
                    <input id="crud-form-1" type="text" name="title" class="form-control form-control-rounded w-full" placeholder="Tiêu đề của mail">
                </div>
                <div class="mt-3">
                    <label for="crud-form-1" class="form-label">Tên người gửi</label>
                    <input id="crud-form-1" type="text" name="sender" class="form-control form-control-rounded w-full" placeholder="Tên của người sẽ gửi mail cho bạn">
                </div>
                <div class="mt-3">
                    <label>Nội dung của mail</label>
                    <div class="mt-2">
                        <textarea name="content" id="myeditorinstance">Hello, World!</textarea>
                    </div>
                </div>
                <input type="hidden" name="date" id="date">
                <input type="hidden" name="time" id="time">
                <input type="hidden" name="cron_time" id="repeat_time">
            </div>
        </div>
    </form>

    <div class="intro-y col-span-12 lg:col-span-6">
        <div class="intro-y box">
            <div class="flex flex-col sm:flex-row items-center p-5 border-b border-slate-200/60 dark:border-darkmode-400">
                <h2 class="font-medium text-base mr-auto">Thời gian</h2>
                <div class="form-check form-switch w-full sm:w-auto sm:ml-auto mt-3 sm:mt-0">
                    <label class="form-check-label ml-0" for="show-example-1">Lặp lại</label>
                    <input id="toggle-repeat" class="show-code form-check-input mr-0 ml-3" type="checkbox">
                </div>
            </div>
            <div id="basic-select" class="p-5">
                <div class="preview">
                    <div id="repeat" class="mt-5">
                        <div class="mt-5">
                            <label>Sẽ tự động gửi vào</label>
                            <div class="mt-2">
                                <input id="no_repeat_date" type="text" class="datepicker w-56 mx-auto" data-single-mode="true">
                                <select id="no_repeat_time" data-placeholder="Chọn giờ" class="tom-select w-full mt-5">
                                    @for($i = 0; $i <= 23; $i++)
                                        @if ($i < 10)<option value="0{{$i}}:00">{{$i}} giờ</option>
                                        @else<option value="{{$i}}:00">{{$i}} giờ</option>
                                        @endif
                                    @endfor
                                </select>
                            </div>
                        </div>
                    </div>
{{--                    ===============--}}
                    <div id="no-repeat" class="mt-5" style="display: none">
                        <div class="mt-5">
                            <label>Lặp lại sau mỗi</label>
                            <div class="mt-2">
                                <select id="repeat_queue" data-placeholder="Select your favorite actors" class="tom-select w-full">
                                    <option value="0 */2 * * *">2 giờ</option>
                                    <option value="0 */3 * * *">3 giờ</option>
                                    <option value="0 */4 * * *">4 giờ</option>
                                    <option value="0 */6 * * *">6 giờ</option>
                                    <option value="0 */8 * * *">8 giờ</option>
                                    <option value="0 */12 * * *">12 giờ</option>
                                    <option value="0 0 */1 * *">1 ngày</option>
                                    <option value="0 0 */2 * *">2 ngày</option>
                                    <option value="0 0 */3 * *">3 ngày</option>
                                    <option value="0 0 */4 * *">4 ngày</option>
                                    <option value="0 0 */5 * *">5 ngày</option>
                                    <option value="0 0 */6 * *">6 ngày</option>
                                    <option value="0 0 */7 * *">7 ngày</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="text-right mt-5">
                    <a href="{{route('template.index')}}" type="button" class="btn btn-outline-secondary w-24 mr-1">Hủy</a>
                    <button id="button_submit" type="submit" class="btn btn-primary w-24">Lưu</button>
                </div>
            </div>
        </div>
    </div>


    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

@endsection


@section('script')

    <script src="https://cdn.tiny.cloud/1/free/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    <script>
        tinymce.init({
            selector: 'textarea#myeditorinstance',
            @if (isDarkMode())
            content_css: 'tinymce-5-dark',
            skin: 'oxide-dark',
            @endif
            height: 270,
            plugins: 'advcode table checklist image advlist autolink lists link charmap preview codesample imagetool fullscreen',
            toolbar: 'insertfile | blocks| bold italic | fullscreen | image | link | preview | codesample | bullist numlist checklist |  alignleft aligncenter alignright',
            menubar: 'insert view',
            mobile: {
                menubar: true
            },
            setup: function(editor) {
                editor.on('init', function (e) {
                    setTimeout(function() {
                        $("button[tabindex='-1'].tox-notification__dismiss.tox-button.tox-button--naked.tox-button--icon")[0].click()
                    }, 10);

                })
            },
            file_picker_types: 'image',
            file_picker_callback: function (cb, value, meta) {
                var input = document.createElement('input')
                input.setAttribute('type', 'file');
                input.setAttribute('accept', 'image/*')
                input.onchange = function () {
                    var file = this.files[0];
                    var reader = new FileReader()
                    reader.onload = function () {
                        var id = 'blobid' + (new Date()).getTime()
                        var blobCache =  tinymce.activeEditor.editorUpload.blobCache
                        var base64 = reader.result.split(',')[1]
                        var blobInfo = blobCache.create(id, file, base64)
                        blobCache.add(blobInfo)
                        cb(blobInfo.blobUri(), { title: file.name })
                    }
                    reader.readAsDataURL(file)
                }
                input.click()
            },
            content_style: 'body { font-family:Helvetica,Arial,sans-serif; font-size:14px }'
        });
    </script>
    <script>
        $(document).ready(function () {
            $("#toggle-repeat").on('change', function() {
                if($("#toggle-repeat").is(':checked')) {
                    $("#repeat").css('display', 'none')
                    $("#no-repeat").css('display', 'block')
                } else {
                    $("#repeat").css('display', 'block')
                    $("#no-repeat").css('display', 'none')
                }
            })

            $("#button_submit").on('click', function () {
                if ($("#toggle-repeat").is(':checked')) {
                    let repeat_time = $("#repeat_queue").val()
                    $("#date").val(null)
                    $("#time").val(null)
                    $("#repeat_time").val(repeat_time)
                } else {
                    let date = $("#no_repeat_date").val()
                    let time = $("#no_repeat_time").val()
                    $("#date").val(date)
                    $("#time").val(time)
                    $("#repeat_time").val(null)
                }
                $("#form").submit()
            })
        })
    </script>
@endsection

resources/views/app/template/index.blade.php
@extends('app-theme.master')

@section('title')
    Các mẫu tin nhắn
@endsection

@section('content')
    <div class="intro-y col-span-12 flex flex-wrap sm:flex-nowrap items-center mt-2">
        <a href="{{route('template.create')}}" class="btn btn-primary shadow-md mr-2">Thêm mẫu tin nhắn</a>
        <div class="dropdown">
{{--            <button class="dropdown-toggle btn px-2 box" aria-expanded="false" data-tw-toggle="dropdown">--}}
{{--                <span class="w-5 h-5 flex items-center justify-center">--}}
{{--                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" icon-name="plus" class="lucide lucide-plus w-4 h-4" data-lucide="plus"><line x1="12" y1="5" x2="12" y2="19"></line><line x1="5" y1="12" x2="19" y2="12"></line></svg>--}}
{{--                </span>--}}
{{--            </button>--}}
            <div class="dropdown-menu w-40">
                <ul class="dropdown-content">
                    <li>
                        <a href="" class="dropdown-item">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" icon-name="printer" data-lucide="printer" class="lucide lucide-printer w-4 h-4 mr-2"><polyline points="6 9 6 2 18 2 18 9"></polyline><path d="M6 18H4a2 2 0 01-2-2v-5a2 2 0 012-2h16a2 2 0 012 2v5a2 2 0 01-2 2h-2"></path><rect x="6" y="14" width="12" height="8"></rect></svg> Print
                        </a>
                    </li>
                    <li>
                        <a href="" class="dropdown-item">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" icon-name="file-text" data-lucide="file-text" class="lucide lucide-file-text w-4 h-4 mr-2"><path d="M14.5 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V7.5L14.5 2z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><line x1="10" y1="9" x2="8" y2="9"></line></svg> Export to Excel
                        </a>
                    </li>
                    <li>
                        <a href="" class="dropdown-item">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" icon-name="file-text" data-lucide="file-text" class="lucide lucide-file-text w-4 h-4 mr-2"><path d="M14.5 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V7.5L14.5 2z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><line x1="10" y1="9" x2="8" y2="9"></line></svg> Export to PDF
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <!-- BEGIN: Users Layout -->

    @foreach($templates as $template)
    <div class="intro-y col-span-12 md:col-span-6 lg:col-span-4">
        <div class="box zoom-in">
            <div class="p-5">
                <div class="h-40 2xl:h-56 image-fit rounded-md overflow-hidden before:block before:absolute before:w-full before:h-full before:top-0 before:left-0 before:z-10 before:bg-gradient-to-t before:from-black before:to-black/10">
                    <img alt="Midone - HTML Admin Template" class="rounded-md" src="{{$template->banner}}">
                    <span class="absolute top-0 bg-pending/80 text-white text-xs m-5 px-2 py-1 rounded z-10">
                        @if (isset($template->schedule->cron_time)) Lặp @else Không lặp @endif
                    </span>
                    <div class="absolute bottom-0 text-white px-5 pb-6 z-10">
                        <a href="" class="block font-medium text-base">{{$template->title}}</a>
                        <span class="text-white/90 text-xs mt-3">{{$template->sender}}</span>
                    </div>
                </div>
                <div class="text-slate-600 dark:text-slate-500 mt-5">
                    <div class="flex items-center">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" icon-name="link" data-lucide="link" class="lucide lucide-link w-4 h-4 mr-2"><path d="M10 13a5 5 0 007.54.54l3-3a5 5 0 00-7.07-7.07l-1.72 1.71"></path><path d="M14 11a5 5 0 00-7.54-.54l-3 3a5 5 0 007.07 7.07l1.71-1.71"></path></svg>
                        Thời gian:
                        @if (isset($template->schedule->cron_time)) {{$template->schedule->beautifulCronTime}} @else {{$template->schedule->dateTime}} @endif

                    </div>
                    <div class="flex items-center mt-2">
                        @if ($template->schedule->active === true)
                            <svg height="24" width="24" viewBox="0 0 38 38" xmlns="http://www.w3.org/2000/svg" class="w-4 h-4 mr-2">
                                <defs>
                                    <linearGradient x1="8.042%" y1="0%" x2="65.682%" y2="23.865%" id="a">
                                        <stop stop-color="rgb(30, 41, 59)" stop-opacity="0" offset="0%"></stop>
                                        <stop stop-color="rgb(30, 41, 59)" stop-opacity=".631" offset="63.146%"></stop>
                                        <stop stop-color="rgb(30, 41, 59)" offset="100%"></stop>
                                    </linearGradient>
                                </defs>
                                <g fill="none" fill-rule="evenodd">
                                    <g transform="translate(1 1)">
                                        <path d="M36 18c0-9.94-8.06-18-18-18" id="Oval-2" stroke="url(#a)" stroke-width="3">
                                            <animateTransform attributeName="transform" type="rotate" from="0 18 18" to="360 18 18" dur="0.9s" repeatCount="indefinite"></animateTransform>
                                        </path>
                                        <circle fill="rgb(30, 41, 59)" cx="36" cy="18" r="1">
                                            <animateTransform attributeName="transform" type="rotate" from="0 18 18" to="360 18 18" dur="0.9s" repeatCount="indefinite"></animateTransform>
                                        </circle>
                                    </g>
                                </g>
                            </svg>
                        @else
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" icon-name="stop-circle" data-lucide="stop-circle" class="lucide lucide-stop-circle w-4 h-4 mr-2"><path d="M10 13a5 5 0 007.54.54l3-3a5 5 0 00-7.07-7.07l-1.72 1.71"></path><path d="M14 11a5 5 0 00-7.54-.54l-3 3a5 5 0 007.07 7.07l1.71-1.71"></path></svg>
                        @endif
                        Trạng thái: {{$template->schedule->nextQueueTime}}
                    </div>
                    <div class="flex items-center mt-2">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" icon-name="check-square" data-lucide="check-square" class="lucide lucide-check-square w-4 h-4 mr-2"><polyline points="9 11 12 14 22 4"></polyline><path d="M21 12v7a2 2 0 01-2 2H5a2 2 0 01-2-2V5a2 2 0 012-2h11"></path></svg>
                        Số lần gửi: {{$template->schedule->count}}
                    </div>
                </div>
            </div>
            <div class="flex justify-center lg:justify-end items-center p-5 border-t border-slate-200/60 dark:border-darkmode-400">
                <form action="{{route('schedule.toggle_active', ['template' => $template])}}" class="form-toggle-active flex items-center text-primary mr-auto" method="post">
                    @method('PUT')
                    @csrf
                    @if ($template->schedule->active === true)
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" icon-name="pause" data-lucide="pause" class="lucide lucide-pause w-4 h-4 mr-1"><polyline points="9 11 12 14 22 4"></polyline><path d="M21 12v7a2 2 0 01-2 2H5a2 2 0 01-2-2V5a2 2 0 012-2h11"></path></svg>
                        Dừng
                    @else
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" icon-name="play" data-lucide="play" class="lucide lucide-play w-4 h-4 mr-1"><polyline points="9 11 12 14 22 4"></polyline><path d="M21 12v7a2 2 0 01-2 2H5a2 2 0 01-2-2V5a2 2 0 012-2h11"></path></svg>
                        Kích hoạt
                    @endif
                </form>
                <a href="{{route('template.edit', ['template' => $template])}}" class="flex items-center mr-3">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" icon-name="check-square" data-lucide="check-square" class="lucide lucide-check-square w-4 h-4 mr-1"><polyline points="9 11 12 14 22 4"></polyline><path d="M21 12v7a2 2 0 01-2 2H5a2 2 0 01-2-2V5a2 2 0 012-2h11"></path></svg>
                    Sửa
                </a>

                <a class="flex items-center text-danger" data-tw-toggle="modal" data-tw-target="#delete-modal-preview-{{$template->id2}}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" icon-name="trash-2" data-lucide="trash-2" class="lucide lucide-trash-2 w-4 h-4 mr-1"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 01-2 2H7a2 2 0 01-2-2V6m3 0V4a2 2 0 012-2h4a2 2 0 012 2v2"></path><line x1="10" y1="11" x2="10" y2="17"></line><line x1="14" y1="11" x2="14" y2="17"></line></svg>
                    Xóa
                </a>
                <div id="delete-modal-preview-{{$template->id2}}" class="modal" tabindex="-1" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-body p-0">
                                <div class="p-5 text-center">
                                    <i data-lucide="x-circle" class="w-16 h-16 text-danger mx-auto mt-3"></i>
                                    <div class="text-3xl mt-5">Xóa mẫu tin nhắn</div>
                                    <div class="text-slate-500 mt-2">Bạn có chắc chắn xóa mẫu tin nhắn? <br>Thao tác này không thể hoàn tác.</div>
                                </div>
                                <div class="px-5 pb-8 text-center">
                                    <form action="{{route('template.destroy', ['template' => $template])}}" method="post">
                                        @csrf
                                        @method('DELETE')
                                        <button type="button" data-tw-dismiss="modal" class="btn btn-outline-secondary w-24 mr-1">Hủy</button>
                                        <button class="btn btn-danger w-24">Xóa</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>


    @endforeach

@endsection

@section('script')
    <script>
        $(document).ready(function () {
            $(".form-toggle-active").click(function () {
                this.submit()
            })
        })
    </script>
@endsection